test:
	nosetests -s -v

run:
	python initGCProject.py

clean-pyc:
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +

help:
	@echo " 	test"
	@echo " 		nosetests the tests."
	@echo " 	run"
	@echo " 		Run main python module."
	@echo " 	clean-pyc"
	@echo " 		Remove python artifacts."
